name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: ./mvnw package

      - name: Check generated JAR
        run: ls -lh target/*.jar

      - name: Upload built JAR
        uses: actions/upload-artifact@v3.1.3
        with:
          name: app-jar
          path: target/*.jar

  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u kpi-devopsgyak --password-stdin

      - name: Download built JAR
        uses: actions/download-artifact@v3.0.2
        with:
          name: app-jar

      - name: Rename JAR to app.jar
        run: mv *.jar app.jar

      - name: Build and push Docker image
        run: |
          docker build . -t ghcr.io/kpi-devopsgyak/cubix/1/homework/app:springboot
          docker push ghcr.io/kpi-devopsgyak/cubix/1/homework/app:springboot

  verify:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u kpi-devopsgyak --password-stdin

      - name: Pull and verify Docker image
        run: |
          chmod +x verify-image.sh
          ./verify-image.sh

#ddd
