name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21 with cache
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: ./mvnw package

      - name: Rename JAR to app.jar
        run: cp target/*.jar app.jar

      - name: Upload app.jar as artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: app.jar

  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download app.jar artifact
        uses: actions/download-artifact@v4
        with:
          name: app-jar

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u kpi-devopsgyak --password-stdin

      - name: Build and push Docker image
        run: |
          docker build . -t ghcr.io/kpi-devopsgyak/cubix/1/homework/app:springboot
          docker push ghcr.io/kpi-devopsgyak/cubix/1/homework/app:springboot

  verify:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u kpi-devopsgyak --password-stdin

      - name: Pull and verify Docker image
        run: ./verify-image.sh
